on: 
  pull_request:
  push:
    branches:    
      - main
  issue_comment:                                     
    types: [created, edited]
name: Scan Secret (go/secret-scanner)
jobs:
  scan_secret:
    name: Scan incoming changes
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue }}
    steps:
      - name: Run scanner
        run: |
          echo ${{ github.sha }}
  verify_allow_list:
    name: Verify allow list
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/verify')
    steps:
      - name: Get PR urls
        run: |
          echo "url: ${{ github.event.issue.pull_request.url }}"
          echo "html_url: ${{ github.event.issue.pull_request.html_url }}"
      - name: Get checked out sha
        run: | 
          echo ${{ github.sha }}
      # - name: Run scanner in verification mode
      #   uses: aristanetworks/secret-scanner-service@beta
      #   with:
      #     mode: verification
