on: 
  pull_request:
  push:
    branches:    
      - main
  issue_comment:                                     
    types: [created, edited]
name: Scan Secret (go/secret-scanner)
jobs:
  scan_secret:
    name: Scan incoming changes
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue }}
    steps:
      - name: Run scanner
        run: |
          echo ${{ github.sha }}
  verify_allow_list:
    name: Verify allow list
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/verify')
    steps:
      - name: Get PR merge commit ref
        id: merge-commit-ref
        run: |
          mergeCommitSha=$( \
            curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ github.token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              ${{ github.event.issue.pull_request.url }} \
            | jq ".head.ref" \
          )
          echo "REF=${mergeCommitRef}" >> $GITHUB_OUTPUT
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.merge-commit-ref.outputs.REF }}
          fetch-depth: 0
      - name: Check log
        run: git log --oneline
