on: 
  pull_request:
  push:
    branches:    
      - main
name: Scan Secret (go/secret-scanner)
jobs:
  scan_secret:
    name: Scan incoming changes
    runs-on: ubuntu-latest
    steps:
      - name: Run scanner
        uses: aristanetworks/secret-scanner-service@beta
